export function getMockWallets() {
  return {
    '3J9k...xYz': {
      fullAddress: '0x3J9k1234567890abcdef1234567890xYz',
      network: 'SOL Network',
      status: ['Not Trusted', 'Cautious Explorer', 'Journeyman'],
      lastChecked: 'a minute ago',
      certifiedBy: 'A SOL TEAM',
      predictedTrust: 1.99, // Out of 100%
      experienceLevel: 5, // Out of 10
      riskWillingness: 3, // Out of 10
      amlAnalysis: {
        cybercrime: false,
        moneyLaundering: false,
        maliciousContracts: 'None',
        financialCrime: false,
        darkWebTransactions: false,
        phishing: false,
        fakeKYC: false,
        stealingAttack: false,
        blackmail: false,
        cryptoJacking: false,
        coinMixerAddress: false,
        fakeToken: false,
        scamToken: false,
      },
      intents: [
        { name: 'Trading', level: 'HIGH' },
        { name: 'Gaming', level: 'MED' },
        { name: 'NFT', level: 'MED' },
        { name: 'Lending', level: 'MED' },
        { name: 'Staking ETH', level: 'MED' },
        { name: 'Borrowing', level: 'LOW' },
        { name: 'Gambling', level: 'LOW' },
        { name: 'Staking', level: 'LOW' },
        { name: 'Yield Farming', level: 'LOW' },
        { name: 'Leveraged Staking ETH', level: 'LOW' },
        { name: 'Leveraged Lending', level: 'LOW' },
        { name: 'Leveraged Long ETH', level: 'LOW' },
      ],
      transactionCategories: [
        { name: 'Decentralized Exchanges', count: 918 },
      ],
      protocols: [
        { name: 'Uniswap', logo: 'uniswap-logo.png' }, // Logo path would need to be an actual asset
      ],
      recommendations: [
        { name: 'WBTC holding', checked: true },
        { name: 'ETH holding', checked: true },
        { name: 'Stablecoin lending', checked: true },
        { name: 'Stablecoin lending with FIFs (SmartCredit.io)', checked: true },
      ],
      fundingSources: ['ExchangeX', '5K2m...aBc', '9P4q...mNo'],
      history: [
        { id: 'tx1', date: '2025-03-15', amount: '50 ETH', type: 'Incoming' },
        { id: 'tx3', date: '2025-04-01', amount: '20 ETH', type: 'Outgoing' },
      ],
      patterns: 'High volume, Suspicious',
      risk: 'High',
      balance: '70 ETH',
    },
    '5K2m...aBc': {
      fullAddress: '0x5K2mabcdef1234567890abcdefaBc',
      network: 'ETH Network',
      status: ['Trusted', 'Experienced Trader'],
      lastChecked: '2 minutes ago',
      certifiedBy: 'A SOL TEAM',
      predictedTrust: 85.5,
      experienceLevel: 8,
      riskWillingness: 6,
      amlAnalysis: {
        cybercrime: false,
        moneyLaundering: false,
        maliciousContracts: 'None',
        financialCrime: false,
        darkWebTransactions: false,
        phishing: false,
        fakeKYC: false,
        stealingAttack: false,
        blackmail: false,
        cryptoJacking: false,
        coinMixerAddress: false,
        fakeToken: false,
        scamToken: false,
      },
      intents: [
        { name: 'Trading', level: 'HIGH' },
        { name: 'Staking', level: 'MED' },
        { name: 'NFT', level: 'LOW' },
        { name: 'Lending', level: 'LOW' },
        { name: 'Staking ETH', level: 'LOW' },
        { name: 'Borrowing', level: 'LOW' },
        { name: 'Gambling', level: 'LOW' },
        { name: 'Gaming', level: 'LOW' },
        { name: 'Yield Farming', level: 'LOW' },
        { name: 'Leveraged Staking ETH', level: 'LOW' },
        { name: 'Leveraged Lending', level: 'LOW' },
        { name: 'Leveraged Long ETH', level: 'LOW' },
      ],
      transactionCategories: [
        { name: 'Decentralized Exchanges', count: 320 },
      ],
      protocols: [
        { name: 'Uniswap', logo: 'uniswap-logo.png' },
      ],
      recommendations: [
        { name: 'ETH holding', checked: true },
        { name: 'Stablecoin lending', checked: true },
      ],
      fundingSources: ['3J9k...xYz', 'ExchangeY'],
      history: [
        { id: 'tx1', date: '2025-03-15', amount: '50 ETH', type: 'Outgoing' },
        { id: 'tx2', date: '2025-03-20', amount: '10 ETH', type: 'Incoming' },
      ],
      patterns: 'Relay',
      risk: 'Medium',
      balance: '40 ETH',
    },
    '7L8n...pQr': {
      fullAddress: '0x7L8n9876543210fedcba9876543pQr',
      network: 'ETH Network',
      status: ['Not Trusted', 'Cautious Explorer'],
      lastChecked: '5 minutes ago',
      certifiedBy: 'A SOL TEAM',
      predictedTrust: 10.2,
      experienceLevel: 3,
      riskWillingness: 2,
      amlAnalysis: {
        cybercrime: true,
        moneyLaundering: false,
        maliciousContracts: '2',
        financialCrime: false,
        darkWebTransactions: true,
        phishing: false,
        fakeKYC: false,
        stealingAttack: false,
        blackmail: false,
        cryptoJacking: false,
        coinMixerAddress: true,
        fakeToken: false,
        scamToken: false,
      },
      intents: [
        { name: 'Gambling', level: 'HIGH' },
        { name: 'Trading', level: 'MED' },
        { name: 'NFT', level: 'LOW' },
        { name: 'Lending', level: 'LOW' },
        { name: 'Staking ETH', level: 'LOW' },
        { name: 'Borrowing', level: 'LOW' },
        { name: 'Gaming', level: 'LOW' },
        { name: 'Staking', level: 'LOW' },
        { name: 'Yield Farming', level: 'LOW' },
        { name: 'Leveraged Staking ETH', level: 'LOW' },
        { name: 'Leveraged Lending', level: 'LOW' },
        { name: 'Leveraged Long ETH', level: 'LOW' },
      ],
      transactionCategories: [
        { name: 'Decentralized Exchanges', count: 150 },
      ],
      protocols: [
        { name: 'Uniswap', logo: 'uniswap-logo.png' },
      ],
      recommendations: [
        { name: 'ETH holding', checked: true },
      ],
      fundingSources: ['5K2m...aBc', '3J9k...xYz', 'MixerZ'],
      history: [
        { id: 'tx2', date: '2025-03-20', amount: '10 ETH', type: 'Outgoing' },
        { id: 'tx4', date: '2025-04-10', amount: '5 ETH', type: 'Incoming' },
      ],
      patterns: 'Sink, Potential Mixer Use',
      risk: 'High',
      balance: '15 ETH',
    },
    '9P4q...mNo': {
      fullAddress: '0x9P4qfedcba9876543210fedcbamNo',
      network: 'ETH Network',
      status: ['Trusted'],
      lastChecked: '10 minutes ago',
      certifiedBy: 'A SOL TEAM',
      predictedTrust: 92.3,
      experienceLevel: 7,
      riskWillingness: 4,
      amlAnalysis: {
        cybercrime: false,
        moneyLaundering: false,
        maliciousContracts: 'None',
        financialCrime: false,
        darkWebTransactions: false,
        phishing: false,
        fakeKYC: false,
        stealingAttack: false,
        blackmail: false,
        cryptoJacking: false,
        coinMixerAddress: false,
        fakeToken: false,
        scamToken: false,
      },
      intents: [
        { name: 'Trading', level: 'MED' },
        { name: 'Staking', level: 'MED' },
        { name: 'NFT', level: 'LOW' },
        { name: 'Lending', level: 'LOW' },
        { name: 'Staking ETH', level: 'LOW' },
        { name: 'Borrowing', level: 'LOW' },
        { name: 'Gambling', level: 'LOW' },
        { name: 'Gaming', level: 'LOW' },
        { name: 'Yield Farming', level: 'LOW' },
        { name: 'Leveraged Staking ETH', level: 'LOW' },
        { name: 'Leveraged Lending', level: 'LOW' },
        { name: 'Leveraged Long ETH', level: 'LOW' },
      ],
      transactionCategories: [
        { name: 'Decentralized Exchanges', count: 50 },
      ],
      protocols: [
        { name: 'Uniswap', logo: 'uniswap-logo.png' },
      ],
      recommendations: [
        { name: 'ETH holding', checked: true },
        { name: 'Stablecoin lending', checked: true },
      ],
      fundingSources: ['ExchangeX'],
      history: [
        { id: 'tx5', date: '2025-04-05', amount: '30 ETH', type: 'Incoming' },
      ],
      patterns: 'Low Activity',
      risk: 'Low',
      balance: '30 ETH',
    },
  };
}